[tool.poetry]
name = "current"
version = "0.1.0"
description = ""
authors = ["George L. F. Harris <glfharris@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
<<<<<<< HEAD
fastapi = "^0.109.2"
uvicorn = "^0.27.1"
=======
gcsa = "^2.2.0"
>>>>>>> ca01b03fdc0a0eedd17f77f10a214dbca0e51f8b


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
